package model

// 查询项目清单数据
var getUserCIDSqlByPlm = "SELECT CID as cid,CNAME as cname from MBP_USER WHERE cusername in ('6039485','6046051','6048379','6039558','6036560','6042724','6039406','6042316','6039379','6048378','6048377','6048376','6046748')"

// GetProductGroup 查询我管理的项目
var GetProductGroup = "SELECT CVERSIONGROUP FROM EAP.MBP_PROJECT_USERROLEREL WHERE CROLEID='PROJECT_MANAGER' AND CUSERID IN "

// GetProductLists 查询项目清单
var GetProductLists = "SELECT * FROM EAP.MBP_PROJECT WHERE CVERSIONGROUP in "

// GetProductTask 项目任务
var GetProductTask = "SELECT * FROM EAP.MBP_PROJECT MP left join MBP_PROJECT_PARENTCHILDREL MPP ON MP.CVERSIONGROUP=MPP.CVERSIONGROUP LEFT JOIN MBP_PROJECT_EXTEND MPE ON MPE.cid=MP.cid WHERE MPP.CPROJECTID = '%s' order by MPP.cindex"

// GetTaskByConnect 根据关联关系查询项目任务
var GetTaskByConnect = "SELECT CVERSIONGROUP from EAP.MBP_PROJECT_PARENTCHILDREL WHERE CPARENTTASKID = '%s' ORDER BY CINDEX ASC"

// GetTaskInfoByVersion 查询项目任务
var GetTaskInfoByVersion = "SELECT MP.CID,MP.CNAME,MP.CTASKSTATUS,MP.CISPROJECT,MP.CVERSIONGROUP,MPP.CPARENTTASKID,MPP.CPROJECTID,'' as children FROM EAP.MBP_PROJECT MP left join EAP.MBP_PROJECT_PARENTCHILDREL MPP ON MP.CVERSIONGROUP=MPP.CVERSIONGROUP WHERE MPP.CPARENTTASKID='%s' order by MPP.cindex"

// GetFileByTask 查询任务下面交付物
var GetFileByTask = "SELECT MDE.CID,MP.CID as PROJECTID,MD.CVERSION,MDE.CNAME,MDE.CSYMBOL,MMO.CNAME as CLASSNAME FROM EAP.MBP_PROJECT MP LEFT JOIN EAP.MBP_PROJECT_WORKOBJ MPW ON MPW.CVERSIONGROUP=MP.CVERSIONGROUP LEFT JOIN EAP.MBP_DOC MD ON MD.CID=MPW.COBJID LEFT JOIN EAP.MBP_DOC_EXTEND MDE ON MD.CID=MDE.CID LEFT JOIN EAP.MBP_META_OBJCLS MMO ON MMO.CID=MD.COBJCLASSID WHERE MP.CID = '%s'"

/*******文档类查询SQL***********/

// GetCompany 查询赣锋重庆
var GetCompany = "SELECT cid as Value ,cname as Text ,CINDEX FROM EAP.MBP_META_DOMAIN WHERE CPARENTID='DEFAULTDOMAIN' AND ctype=1 AND CINDEX=%s"

// GetCompanyProductCate 查询公司下面项目管理版块文档目录
var GetCompanyProductCate = "SELECT CID,CTYPE,CNAME FROM EAP.MBP_META_DOMAIN WHERE ctype = 1 AND CPARENTID='%s' ORDER BY CINDEX ASC"

// GetProductListByCate 查询项目目录下项目清单
var GetProductListByCate = "SELECT CID,CNAME,CPARENTID,CUSESTATE FROM EAP.MBP_META_OBJCLS WHERE CID IN (SELECT CID FROM EAP.MBP_META_DOMAIN WHERE CPARENTID = '%s') ORDER BY CNAME ASC"

// GetProductFileListWithoutFilePath 查询项目下文件清单(不包含文件路径)
var GetProductFileListWithoutFilePath = "SELECT D.CID,DE.CNAME,DE.CSYMBOL,DE.CSUFFIX,D.CVERSION,D.CPUBLISHTIME,D.CISLATESTPUBLISHED,DE.FGKBM,DE.FGGJL,DE.FXMJD FROM EAP.MBP_DOC D INNER JOIN EAP.MBP_DOC_EXTEND DE ON D.CID=DE.CID WHERE D.COBJCLASSID = '%s' AND D.CSTATE=200"

// GetProductPlanFile 查询项目二级开发计划
var GetProductPlanFile = "SELECT D.CID,DE.CNAME,DE.CSYMBOL,DE.CSUFFIX,D.CVERSION,D.CPUBLISHTIME,D.CISLATESTPUBLISHED,DE.FGKBM,DE.FGGJL,DE.FXMJD FROM EAP.MBP_DOC D INNER JOIN EAP.MBP_DOC_EXTEND DE ON D.CID=DE.CID WHERE D.COBJCLASSID = '%s' AND CNAME LIKE '%s' AND D.CSTATE = 200"

// GetProductFileList 查询项目下文件清单
var GetProductFileList = "SELECT DE.CNAME,DE.CSYMBOL,DE.CSUFFIX,D.CVERSION,D.CPUBLISHTIME,D.CISLATESTPUBLISHED,DM.CFILENAME,DM.CREMARK,DM.CFILELOCATION,DM.CRELATIVEPATH,DE.FGKBM,DE.FGGJL,DE.FXMJD FROM EAP.MBP_DOC D LEFT JOIN EAP.MBP_DOC_EXTEND DE ON D.CID=DE.CID INNER JOIN EAP.MBP_DOCFILEMAIN DM ON D.CID=DM.CDOCID WHERE D.COBJCLASSID = '%s' AND DM.CSTATE=1"
