# 构建golang运行环境 使用别名：builder
FROM golang:1.18 as builder

# 设置环境变量
ENV HOME /app
ENV CGO_ENABLED 1
ENV GOOS linux
ENV GO111MODULE on
ENV GOPROXY https://goproxy.cn,direct

# 设置工作目录 - 我们所有的文件都存放在工作目录中
WORKDIR /app
COPY . .

RUN ls
# 下载依赖
RUN go mod tidy

# 编译app
RUN go build -o main main.go


################################################################################
##                                   START
################################################################################
FROM loads/alpine:3.8
LABEL maintainer="1570693659@qq.com"

RUN apk --no-cache add ca-certificates

# 设置工作目录
ENV WORKDIR /app/tools_product

# 将上个容器编译的二进制文件复制到 工作目录
# 也就是：copy golang环境/工作目录/demo alpine环境/工作目录
COPY --from=builder /app/main $WORKDIR/main
RUN mkdir -p $WORKDIR/config/
COPY --from=builder /app/config/config_pro.toml $WORKDIR/config/config.toml
RUN mkdir -p $WORKDIR/public/
COPY --from=builder /app/public/ $WORKDIR/public/
RUN mkdir -p $WORKDIR/packed/
COPY --from=builder /app/packed/ $WORKDIR/packed/

RUN chmod +x $WORKDIR/main
RUN chmod +x $WORKDIR/config/config.toml
RUN chmod +x $WORKDIR/packed/getMpp.py
RUN ls

# 所以这里执行的命令是：/bin/demo
WORKDIR $WORKDIR
CMD ./main