version: '3.1'
services:
  master:
    image: registry.cn-hangzhou.aliyuncs.com/helowin/oracle_11g
    container_name: oracle
    privileged: true
    ports:
      - 11521:1521
    volumes:
      - ../../helowin/:/home/oracle/app/oracle/oradata/helowin/