# HTTP Server.
[server]
	address        = ":8130"
	serverRoot     = "public"
	serverAgent    = "gfcq_tools_product"
	logPath        = "/tmp/log/gfcq_tools_product/server"
	nameToUriType  = 2
	routeOverWrite = true

# Logger configurations.
[logger]
    path   = "D:/code/product/golang/src/gfcq_tools_product/tmp/log/gfcq_tools_product"
    level  = "all"
    stdout = true
    file = "{Y-m-d}.log"
    rotateSize = "100M"
    rotateBackupLimit = 10
    rotateBackupExpire = "60d"
    rotateBackupCompress = 9
    rotateCheckInterval = "24h"

# Database configurations.
[database]
    [database.plm]
        link = "PLM_USER_READ/iK35vtqAvRTsc8c@10.14.37.19:1521/GFPLM?charset=utf8mb4&parseTime=True&loc=Local"
        database = "EAP"
        debug = true
        stdout = true
    [database.mongo]
        link = "localhost:27017"
        debug = true
        stdout = true
    # 数据库日志对象配置
    [database.logger]
        level  = "all"
        stdout = true

[deliverable]
    keyMateRate = 0.7
    planFileName = "二级开发计划"
    fileUrl = "http://10.127.180.11:8080/api/GFLD/DowloadFile?docobjid=%s&docobjclassid=%s&doctype=2"

[plm]
    companyIndex = 17
    companyObjId = "9700123a-9abd-4364-a022-f74400068976"

[grpc]
    [grpc.organize]
        name = "organize"
        link = "127.0.0.1:9090"
    [grpc.config]
        name = "gfcq_config"
        link = "127.0.0.1:9080"
